package com.coe.declare.login.entity;

import java.util.Date;

public class LoginUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_user.id
     *
     * @mbggenerated Thu Jan 12 14:58:02 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_user.role_id
     *
     * @mbggenerated Thu Jan 12 14:58:02 CST 2017
     */
    private Long roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_user.user_name
     *
     * @mbggenerated Thu Jan 12 14:58:02 CST 2017
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_user.password
     *
     * @mbggenerated Thu Jan 12 14:58:02 CST 2017
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_user.mobile
     *
     * @mbggenerated Thu Jan 12 14:58:02 CST 2017
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_user.age
     *
     * @mbggenerated Thu Jan 12 14:58:02 CST 2017
     */
    private Integer age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_user.sex
     *
     * @mbggenerated Thu Jan 12 14:58:02 CST 2017
     */
    private Integer sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_user.last_login_time
     *
     * @mbggenerated Thu Jan 12 14:58:02 CST 2017
     */
    private Long lastLoginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_user.last_out_time
     *
     * @mbggenerated Thu Jan 12 14:58:02 CST 2017
     */
    private Long lastOutTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_user.is_valid
     *
     * @mbggenerated Thu Jan 12 14:58:02 CST 2017
     */
    private Integer isValid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_user.remark
     *
     * @mbggenerated Thu Jan 12 14:58:02 CST 2017
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_user.create_time
     *
     * @mbggenerated Thu Jan 12 14:58:02 CST 2017
     */
    private Long createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_user.real_name
     *
     * @mbggenerated Thu Jan 12 14:58:02 CST 2017
     */
    private String realName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_user.last_login_ip
     *
     * @mbggenerated Thu Jan 12 14:58:02 CST 2017
     */
    private String lastLoginIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_user.update_time
     *
     * @mbggenerated Thu Jan 12 14:58:02 CST 2017
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_user.create_user_name
     *
     * @mbggenerated Thu Jan 12 14:58:02 CST 2017
     */
    private String createUserName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_user.role_name
     *
     * @mbggenerated Thu Jan 12 14:58:02 CST 2017
     */
    private String roleName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_user.id
     *
     * @return the value of login_user.id
     *
     * @mbggenerated Thu Jan 12 14:58:02 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_user.id
     *
     * @param id the value for login_user.id
     *
     * @mbggenerated Thu Jan 12 14:58:02 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_user.role_id
     *
     * @return the value of login_user.role_id
     *
     * @mbggenerated Thu Jan 12 14:58:02 CST 2017
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_user.role_id
     *
     * @param roleId the value for login_user.role_id
     *
     * @mbggenerated Thu Jan 12 14:58:02 CST 2017
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_user.user_name
     *
     * @return the value of login_user.user_name
     *
     * @mbggenerated Thu Jan 12 14:58:02 CST 2017
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_user.user_name
     *
     * @param userName the value for login_user.user_name
     *
     * @mbggenerated Thu Jan 12 14:58:02 CST 2017
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_user.password
     *
     * @return the value of login_user.password
     *
     * @mbggenerated Thu Jan 12 14:58:02 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_user.password
     *
     * @param password the value for login_user.password
     *
     * @mbggenerated Thu Jan 12 14:58:02 CST 2017
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_user.mobile
     *
     * @return the value of login_user.mobile
     *
     * @mbggenerated Thu Jan 12 14:58:02 CST 2017
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_user.mobile
     *
     * @param mobile the value for login_user.mobile
     *
     * @mbggenerated Thu Jan 12 14:58:02 CST 2017
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_user.age
     *
     * @return the value of login_user.age
     *
     * @mbggenerated Thu Jan 12 14:58:02 CST 2017
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_user.age
     *
     * @param age the value for login_user.age
     *
     * @mbggenerated Thu Jan 12 14:58:02 CST 2017
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_user.sex
     *
     * @return the value of login_user.sex
     *
     * @mbggenerated Thu Jan 12 14:58:02 CST 2017
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_user.sex
     *
     * @param sex the value for login_user.sex
     *
     * @mbggenerated Thu Jan 12 14:58:02 CST 2017
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_user.last_login_time
     *
     * @return the value of login_user.last_login_time
     *
     * @mbggenerated Thu Jan 12 14:58:02 CST 2017
     */
    public Long getLastLoginTime() {
        return lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_user.last_login_time
     *
     * @param lastLoginTime the value for login_user.last_login_time
     *
     * @mbggenerated Thu Jan 12 14:58:02 CST 2017
     */
    public void setLastLoginTime(Long lastLoginTime) {
        this.lastLoginTime = lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_user.last_out_time
     *
     * @return the value of login_user.last_out_time
     *
     * @mbggenerated Thu Jan 12 14:58:02 CST 2017
     */
    public Long getLastOutTime() {
        return lastOutTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_user.last_out_time
     *
     * @param lastOutTime the value for login_user.last_out_time
     *
     * @mbggenerated Thu Jan 12 14:58:02 CST 2017
     */
    public void setLastOutTime(Long lastOutTime) {
        this.lastOutTime = lastOutTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_user.is_valid
     *
     * @return the value of login_user.is_valid
     *
     * @mbggenerated Thu Jan 12 14:58:02 CST 2017
     */
    public Integer getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_user.is_valid
     *
     * @param isValid the value for login_user.is_valid
     *
     * @mbggenerated Thu Jan 12 14:58:02 CST 2017
     */
    public void setIsValid(Integer isValid) {
        this.isValid = isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_user.remark
     *
     * @return the value of login_user.remark
     *
     * @mbggenerated Thu Jan 12 14:58:02 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_user.remark
     *
     * @param remark the value for login_user.remark
     *
     * @mbggenerated Thu Jan 12 14:58:02 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_user.create_time
     *
     * @return the value of login_user.create_time
     *
     * @mbggenerated Thu Jan 12 14:58:02 CST 2017
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_user.create_time
     *
     * @param createTime the value for login_user.create_time
     *
     * @mbggenerated Thu Jan 12 14:58:02 CST 2017
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_user.real_name
     *
     * @return the value of login_user.real_name
     *
     * @mbggenerated Thu Jan 12 14:58:02 CST 2017
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_user.real_name
     *
     * @param realName the value for login_user.real_name
     *
     * @mbggenerated Thu Jan 12 14:58:02 CST 2017
     */
    public void setRealName(String realName) {
        this.realName = realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_user.last_login_ip
     *
     * @return the value of login_user.last_login_ip
     *
     * @mbggenerated Thu Jan 12 14:58:02 CST 2017
     */
    public String getLastLoginIp() {
        return lastLoginIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_user.last_login_ip
     *
     * @param lastLoginIp the value for login_user.last_login_ip
     *
     * @mbggenerated Thu Jan 12 14:58:02 CST 2017
     */
    public void setLastLoginIp(String lastLoginIp) {
        this.lastLoginIp = lastLoginIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_user.update_time
     *
     * @return the value of login_user.update_time
     *
     * @mbggenerated Thu Jan 12 14:58:02 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_user.update_time
     *
     * @param updateTime the value for login_user.update_time
     *
     * @mbggenerated Thu Jan 12 14:58:02 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_user.create_user_name
     *
     * @return the value of login_user.create_user_name
     *
     * @mbggenerated Thu Jan 12 14:58:02 CST 2017
     */
    public String getCreateUserName() {
        return createUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_user.create_user_name
     *
     * @param createUserName the value for login_user.create_user_name
     *
     * @mbggenerated Thu Jan 12 14:58:02 CST 2017
     */
    public void setCreateUserName(String createUserName) {
        this.createUserName = createUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_user.role_name
     *
     * @return the value of login_user.role_name
     *
     * @mbggenerated Thu Jan 12 14:58:02 CST 2017
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_user.role_name
     *
     * @param roleName the value for login_user.role_name
     *
     * @mbggenerated Thu Jan 12 14:58:02 CST 2017
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }
}