package com.coe.message.entity;

import java.util.Date;

public class MessageResponseNewest {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_response_newest.id
     *
     * @mbggenerated Thu Dec 29 14:03:46 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_response_newest.message_id
     *
     * @mbggenerated Thu Dec 29 14:03:46 CST 2016
     */
    private Long messageId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_response_newest.http_status
     *
     * @mbggenerated Thu Dec 29 14:03:46 CST 2016
     */
    private Integer httpStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_response_newest.send_begin_time
     *
     * @mbggenerated Thu Dec 29 14:03:46 CST 2016
     */
    private Long sendBeginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_response_newest.send_end_time
     *
     * @mbggenerated Thu Dec 29 14:03:46 CST 2016
     */
    private Long sendEndTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_response_newest.used_time
     *
     * @mbggenerated Thu Dec 29 14:03:46 CST 2016
     */
    private Long usedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_response_newest.status
     *
     * @mbggenerated Thu Dec 29 14:03:46 CST 2016
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_response_newest.status_desc
     *
     * @mbggenerated Thu Dec 29 14:03:46 CST 2016
     */
    private String statusDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_response_newest.created_time
     *
     * @mbggenerated Thu Dec 29 14:03:46 CST 2016
     */
    private Date createdTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_response_newest.id
     *
     * @return the value of message_response_newest.id
     *
     * @mbggenerated Thu Dec 29 14:03:46 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_response_newest.id
     *
     * @param id the value for message_response_newest.id
     *
     * @mbggenerated Thu Dec 29 14:03:46 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_response_newest.message_id
     *
     * @return the value of message_response_newest.message_id
     *
     * @mbggenerated Thu Dec 29 14:03:46 CST 2016
     */
    public Long getMessageId() {
        return messageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_response_newest.message_id
     *
     * @param messageId the value for message_response_newest.message_id
     *
     * @mbggenerated Thu Dec 29 14:03:46 CST 2016
     */
    public void setMessageId(Long messageId) {
        this.messageId = messageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_response_newest.http_status
     *
     * @return the value of message_response_newest.http_status
     *
     * @mbggenerated Thu Dec 29 14:03:46 CST 2016
     */
    public Integer getHttpStatus() {
        return httpStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_response_newest.http_status
     *
     * @param httpStatus the value for message_response_newest.http_status
     *
     * @mbggenerated Thu Dec 29 14:03:46 CST 2016
     */
    public void setHttpStatus(Integer httpStatus) {
        this.httpStatus = httpStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_response_newest.send_begin_time
     *
     * @return the value of message_response_newest.send_begin_time
     *
     * @mbggenerated Thu Dec 29 14:03:46 CST 2016
     */
    public Long getSendBeginTime() {
        return sendBeginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_response_newest.send_begin_time
     *
     * @param sendBeginTime the value for message_response_newest.send_begin_time
     *
     * @mbggenerated Thu Dec 29 14:03:46 CST 2016
     */
    public void setSendBeginTime(Long sendBeginTime) {
        this.sendBeginTime = sendBeginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_response_newest.send_end_time
     *
     * @return the value of message_response_newest.send_end_time
     *
     * @mbggenerated Thu Dec 29 14:03:46 CST 2016
     */
    public Long getSendEndTime() {
        return sendEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_response_newest.send_end_time
     *
     * @param sendEndTime the value for message_response_newest.send_end_time
     *
     * @mbggenerated Thu Dec 29 14:03:46 CST 2016
     */
    public void setSendEndTime(Long sendEndTime) {
        this.sendEndTime = sendEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_response_newest.used_time
     *
     * @return the value of message_response_newest.used_time
     *
     * @mbggenerated Thu Dec 29 14:03:46 CST 2016
     */
    public Long getUsedTime() {
        return usedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_response_newest.used_time
     *
     * @param usedTime the value for message_response_newest.used_time
     *
     * @mbggenerated Thu Dec 29 14:03:46 CST 2016
     */
    public void setUsedTime(Long usedTime) {
        this.usedTime = usedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_response_newest.status
     *
     * @return the value of message_response_newest.status
     *
     * @mbggenerated Thu Dec 29 14:03:46 CST 2016
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_response_newest.status
     *
     * @param status the value for message_response_newest.status
     *
     * @mbggenerated Thu Dec 29 14:03:46 CST 2016
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_response_newest.status_desc
     *
     * @return the value of message_response_newest.status_desc
     *
     * @mbggenerated Thu Dec 29 14:03:46 CST 2016
     */
    public String getStatusDesc() {
        return statusDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_response_newest.status_desc
     *
     * @param statusDesc the value for message_response_newest.status_desc
     *
     * @mbggenerated Thu Dec 29 14:03:46 CST 2016
     */
    public void setStatusDesc(String statusDesc) {
        this.statusDesc = statusDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_response_newest.created_time
     *
     * @return the value of message_response_newest.created_time
     *
     * @mbggenerated Thu Dec 29 14:03:46 CST 2016
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_response_newest.created_time
     *
     * @param createdTime the value for message_response_newest.created_time
     *
     * @mbggenerated Thu Dec 29 14:03:46 CST 2016
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }
}