package com.coe.message.entity;

public class MessageResponseNewestWithBLOBs extends MessageResponseNewest {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_response_newest.response_header
     *
     * @mbggenerated Thu Dec 29 14:03:46 CST 2016
     */
    private String responseHeader;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_response_newest.response_body
     *
     * @mbggenerated Thu Dec 29 14:03:46 CST 2016
     */
    private String responseBody;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_response_newest.response_header
     *
     * @return the value of message_response_newest.response_header
     *
     * @mbggenerated Thu Dec 29 14:03:46 CST 2016
     */
    public String getResponseHeader() {
        return responseHeader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_response_newest.response_header
     *
     * @param responseHeader the value for message_response_newest.response_header
     *
     * @mbggenerated Thu Dec 29 14:03:46 CST 2016
     */
    public void setResponseHeader(String responseHeader) {
        this.responseHeader = responseHeader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_response_newest.response_body
     *
     * @return the value of message_response_newest.response_body
     *
     * @mbggenerated Thu Dec 29 14:03:46 CST 2016
     */
    public String getResponseBody() {
        return responseBody;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_response_newest.response_body
     *
     * @param responseBody the value for message_response_newest.response_body
     *
     * @mbggenerated Thu Dec 29 14:03:46 CST 2016
     */
    public void setResponseBody(String responseBody) {
        this.responseBody = responseBody;
    }
}