package com.coe.message.dao.mapper;

import com.coe.message.entity.MessageRequest;
import com.coe.message.entity.MessageRequestExample;
import com.coe.message.entity.MessageRequestWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MessageRequestMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_request
     *
     * @mbggenerated Thu Dec 29 13:54:39 CST 2016
     */
    int countByExample(MessageRequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_request
     *
     * @mbggenerated Thu Dec 29 13:54:39 CST 2016
     */
    int deleteByExample(MessageRequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_request
     *
     * @mbggenerated Thu Dec 29 13:54:39 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_request
     *
     * @mbggenerated Thu Dec 29 13:54:39 CST 2016
     */
    int insert(MessageRequestWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_request
     *
     * @mbggenerated Thu Dec 29 13:54:39 CST 2016
     */
    int insertSelective(MessageRequestWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_request
     *
     * @mbggenerated Thu Dec 29 13:54:39 CST 2016
     */
    List<MessageRequestWithBLOBs> selectByExampleWithBLOBs(MessageRequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_request
     *
     * @mbggenerated Thu Dec 29 13:54:39 CST 2016
     */
    List<MessageRequest> selectByExample(MessageRequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_request
     *
     * @mbggenerated Thu Dec 29 13:54:39 CST 2016
     */
    MessageRequestWithBLOBs selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_request
     *
     * @mbggenerated Thu Dec 29 13:54:39 CST 2016
     */
    int updateByExampleSelective(@Param("record") MessageRequestWithBLOBs record, @Param("example") MessageRequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_request
     *
     * @mbggenerated Thu Dec 29 13:54:39 CST 2016
     */
    int updateByExampleWithBLOBs(@Param("record") MessageRequestWithBLOBs record, @Param("example") MessageRequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_request
     *
     * @mbggenerated Thu Dec 29 13:54:39 CST 2016
     */
    int updateByExample(@Param("record") MessageRequest record, @Param("example") MessageRequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_request
     *
     * @mbggenerated Thu Dec 29 13:54:39 CST 2016
     */
    int updateByPrimaryKeySelective(MessageRequestWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_request
     *
     * @mbggenerated Thu Dec 29 13:54:39 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(MessageRequestWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_request
     *
     * @mbggenerated Thu Dec 29 13:54:39 CST 2016
     */
    int updateByPrimaryKey(MessageRequest record);
}