package com.coe.message.dao.mapper;

import com.coe.message.entity.Message;
import com.coe.message.entity.MessageExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface MessageMapper {

	/**保存Message信息返回主键id(返回的主键id，是存在对象中，获取是messge.getId();)*/
	int insertBackId(Message message);

	/**分页查询For api*/
	List<Message> queryPageForApi(Map<String, Object> paramsMap);
	
	/**分页模糊查询*/
	List<Message> queryListPageForVague(Map<String,Object> paramsMap);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table message
	 *
	 * @mbggenerated Wed Jan 11 16:54:01 CST 2017
	 */
	int countByExample(MessageExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table message
	 *
	 * @mbggenerated Wed Jan 11 16:54:01 CST 2017
	 */
	int deleteByExample(MessageExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table message
	 *
	 * @mbggenerated Wed Jan 11 16:54:01 CST 2017
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table message
	 *
	 * @mbggenerated Wed Jan 11 16:54:01 CST 2017
	 */
	int insert(Message record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table message
	 *
	 * @mbggenerated Wed Jan 11 16:54:01 CST 2017
	 */
	int insertSelective(Message record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table message
	 *
	 * @mbggenerated Wed Jan 11 16:54:01 CST 2017
	 */
	List<Message> selectByExample(MessageExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table message
	 *
	 * @mbggenerated Wed Jan 11 16:54:01 CST 2017
	 */
	Message selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table message
	 *
	 * @mbggenerated Wed Jan 11 16:54:01 CST 2017
	 */
	int updateByExampleSelective(@Param("record") Message record, @Param("example") MessageExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table message
	 *
	 * @mbggenerated Wed Jan 11 16:54:01 CST 2017
	 */
	int updateByExample(@Param("record") Message record, @Param("example") MessageExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table message
	 *
	 * @mbggenerated Wed Jan 11 16:54:01 CST 2017
	 */
	int updateByPrimaryKeySelective(Message record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table message
	 *
	 * @mbggenerated Wed Jan 11 16:54:01 CST 2017
	 */
	int updateByPrimaryKey(Message record);
}