package com.coe.message.dao.mapper;

import com.coe.message.entity.MessageResponseNewest;
import com.coe.message.entity.MessageResponseNewestExample;
import com.coe.message.entity.MessageResponseNewestWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MessageResponseNewestMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_response_newest
     *
     * @mbggenerated Thu Dec 29 14:03:46 CST 2016
     */
    int countByExample(MessageResponseNewestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_response_newest
     *
     * @mbggenerated Thu Dec 29 14:03:46 CST 2016
     */
    int deleteByExample(MessageResponseNewestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_response_newest
     *
     * @mbggenerated Thu Dec 29 14:03:46 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_response_newest
     *
     * @mbggenerated Thu Dec 29 14:03:46 CST 2016
     */
    int insert(MessageResponseNewestWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_response_newest
     *
     * @mbggenerated Thu Dec 29 14:03:46 CST 2016
     */
    int insertSelective(MessageResponseNewestWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_response_newest
     *
     * @mbggenerated Thu Dec 29 14:03:46 CST 2016
     */
    List<MessageResponseNewestWithBLOBs> selectByExampleWithBLOBs(MessageResponseNewestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_response_newest
     *
     * @mbggenerated Thu Dec 29 14:03:46 CST 2016
     */
    List<MessageResponseNewest> selectByExample(MessageResponseNewestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_response_newest
     *
     * @mbggenerated Thu Dec 29 14:03:46 CST 2016
     */
    MessageResponseNewestWithBLOBs selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_response_newest
     *
     * @mbggenerated Thu Dec 29 14:03:46 CST 2016
     */
    int updateByExampleSelective(@Param("record") MessageResponseNewestWithBLOBs record, @Param("example") MessageResponseNewestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_response_newest
     *
     * @mbggenerated Thu Dec 29 14:03:46 CST 2016
     */
    int updateByExampleWithBLOBs(@Param("record") MessageResponseNewestWithBLOBs record, @Param("example") MessageResponseNewestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_response_newest
     *
     * @mbggenerated Thu Dec 29 14:03:46 CST 2016
     */
    int updateByExample(@Param("record") MessageResponseNewest record, @Param("example") MessageResponseNewestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_response_newest
     *
     * @mbggenerated Thu Dec 29 14:03:46 CST 2016
     */
    int updateByPrimaryKeySelective(MessageResponseNewestWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_response_newest
     *
     * @mbggenerated Thu Dec 29 14:03:46 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(MessageResponseNewestWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_response_newest
     *
     * @mbggenerated Thu Dec 29 14:03:46 CST 2016
     */
    int updateByPrimaryKey(MessageResponseNewest record);
}