package com.coe.message.dao.mapper;

import com.coe.message.entity.MessageCallback;
import com.coe.message.entity.MessageCallbackExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MessageCallbackMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_callback
     *
     * @mbggenerated Thu Dec 29 13:51:38 CST 2016
     */
    int countByExample(MessageCallbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_callback
     *
     * @mbggenerated Thu Dec 29 13:51:38 CST 2016
     */
    int deleteByExample(MessageCallbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_callback
     *
     * @mbggenerated Thu Dec 29 13:51:38 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_callback
     *
     * @mbggenerated Thu Dec 29 13:51:38 CST 2016
     */
    int insert(MessageCallback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_callback
     *
     * @mbggenerated Thu Dec 29 13:51:38 CST 2016
     */
    int insertSelective(MessageCallback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_callback
     *
     * @mbggenerated Thu Dec 29 13:51:38 CST 2016
     */
    List<MessageCallback> selectByExample(MessageCallbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_callback
     *
     * @mbggenerated Thu Dec 29 13:51:38 CST 2016
     */
    MessageCallback selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_callback
     *
     * @mbggenerated Thu Dec 29 13:51:38 CST 2016
     */
    int updateByExampleSelective(@Param("record") MessageCallback record, @Param("example") MessageCallbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_callback
     *
     * @mbggenerated Thu Dec 29 13:51:38 CST 2016
     */
    int updateByExample(@Param("record") MessageCallback record, @Param("example") MessageCallbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_callback
     *
     * @mbggenerated Thu Dec 29 13:51:38 CST 2016
     */
    int updateByPrimaryKeySelective(MessageCallback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_callback
     *
     * @mbggenerated Thu Dec 29 13:51:38 CST 2016
     */
    int updateByPrimaryKey(MessageCallback record);
}