package com.coe.declare.declare.dao.mapper;

import com.coe.declare.login.entity.LoginUser;
import com.coe.declare.login.entity.LoginUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LoginUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_user
     *
     * @mbggenerated Thu Jan 12 14:58:02 CST 2017
     */
    int countByExample(LoginUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_user
     *
     * @mbggenerated Thu Jan 12 14:58:02 CST 2017
     */
    int deleteByExample(LoginUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_user
     *
     * @mbggenerated Thu Jan 12 14:58:02 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_user
     *
     * @mbggenerated Thu Jan 12 14:58:02 CST 2017
     */
    int insert(LoginUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_user
     *
     * @mbggenerated Thu Jan 12 14:58:02 CST 2017
     */
    int insertSelective(LoginUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_user
     *
     * @mbggenerated Thu Jan 12 14:58:02 CST 2017
     */
    List<LoginUser> selectByExample(LoginUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_user
     *
     * @mbggenerated Thu Jan 12 14:58:02 CST 2017
     */
    LoginUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_user
     *
     * @mbggenerated Thu Jan 12 14:58:02 CST 2017
     */
    int updateByExampleSelective(@Param("record") LoginUser record, @Param("example") LoginUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_user
     *
     * @mbggenerated Thu Jan 12 14:58:02 CST 2017
     */
    int updateByExample(@Param("record") LoginUser record, @Param("example") LoginUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_user
     *
     * @mbggenerated Thu Jan 12 14:58:02 CST 2017
     */
    int updateByPrimaryKeySelective(LoginUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_user
     *
     * @mbggenerated Thu Jan 12 14:58:02 CST 2017
     */
    int updateByPrimaryKey(LoginUser record);
}